from os import environ

vars = Variables(None, ARGUMENTS)
vars.Add('modelflags',
         'Compiler flags for model source code', 
         '-g -O0 -fno-var-tracking --std=c++11')
vars.Add('lorentzflags',
         'Compiler flags for lorentz source code', 
         '-g -O2 -ffast-math --std=c++11')
vars.Add('includedir',
         'Location of SHERPA headers',
         '/cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/sherpa/2.2.11-3accc7eca0049aa5cd49bbe57f88d1a2/include/SHERPA-MC')
vars.Add('libpath',
         'Location of SHERPA libraries',
         '/cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/sherpa/2.2.11-3accc7eca0049aa5cd49bbe57f88d1a2/lib/SHERPA-MC')
vars.Add('installdir',
         'Installation directory for the generated library',
         'ufo_out/')

env = Environment(variables=vars,
                  CPPPATH=['${includedir}'],
                  LIBPATH=['${libdir}'],
                  RPATH  =['${libdir}'])

vars.Update(env)
Help(vars.GenerateHelpText(env))

env['ENV']=environ
if env['PLATFORM']=='darwin':
   env.Append( LINKFLAGS='-Wl,-undefined -Wl,dynamic_lookup' )
else:
   env.Append( LINKFLAGS='-Wl,-no-as-needed' )

lorentz_sources = [ s for s in  env.Glob('*.C') if s.name!='Model.C']

modellib = env.SharedLibrary('SherpaHAHM_variableMW_UFO',[env.SharedObject('Model.C', CXXFLAGS='$modelflags'), 
                                           env.SharedObject(lorentz_sources,CXXFLAGS='$lorentzflags')])

env.Install('${installdir}',modellib)
env.Alias('install',['${installdir}'])
