#!/bin/sh -f
#
# ---------------------------------------------------------
# LSF parameters
# ---------------------------------------------------------
#
set nonomatch
echo ""
echo "Job is running on `uname -a`"
echo "Job started on `date`"
echo ""
echo "Job has been submitted from : " $LS_SUBCWD
#if ( ${OS} != "Solaris" && ${OS} != "Linux" ) exit
#setenv OS_VERS Linux__2.6
#
#----------------------------------------------------------
# S e t t h e r u n t i m e e n v i r o n m e n t
#----------------------------------------------------------
#
echo "Step 1 : Setting the environment"
export SCRAM_ARCH=slc6_amd64_gcc493
export CMSSW_SRC=/afs/cern.ch/work/s/shoh/analysis/SherpaStudies/Sherpa-Generation/CMSSW_9_4_8/src ##terminate at package SherpaGeneration
export CODE_SRC=/afs/cern.ch/work/s/shoh/analysis/SherpaStudies/Sherpa-Generation/CMSSW_9_4_8/src/SherpaGeneration/Sherpacker/batch ##CURRENT
export RUN_CARD=Run.dat_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV
export SherpackLocation=/eos/user/${USER:0:1}/$USER
export CMSSWRELEASE=CMSSW_9_4_8
export nevent=1000
#rm -rf ${CODE_SRC}/CMSSW_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_mphi_INPUT3_mchi__mhs_INPUT4.job

echo "- - - - - PATH SETTING- - - - -"
echo "SCRAM_ARCH is : " ${SCRAM_ARCH}
echo "Current Directory is : " ${CODE_SRC}
echo "WorkDir is : " ${WORKDIR}
echo "Run card is : " ${RUN_CARD}
echo "Sherpack Location is : " ${SherpackLocation}
echo "Disk space on this batch machine:"
df -h
#
#----------------------------------------------------------
# Run CMSSW
#----------------------------------------------------------
#
echo "Step 2 : Run"
#####################################
# Step-1: #
#####################################
echo "Start Step-1: Generator"
cd ${WORKDIR}
scramv1 project CMSSW ${CMSSWRELEASE}
echo "scramv1 complete"
cd ${CMSSWRELEASE}/src
eval `scramv1 runtime -sh`

#populate with necessary packages.
git cms-addpkg -q GeneratorInterface/SherpaInterface
#copy nessecary files
cp -r ${CMSSW_SRC}/SherpaGeneration .
echo "echo ${CMSSW_SRC}"
scram b -j6

#Generate Sherpack
cd SherpaGeneration/Sherpacker/test
#scp ../data/Inclusives/${RUN_CARD} .
#scp ./${RUN_CARD} .
ls
echo "Running run_MakeSherpaLibs.sh WtoMNu_2j_LO_OpenLoops_CKKW_13TeV"
sh run_MakeSherpaLibs.sh WtoMNu_2j_LO_OpenLoops_CKKW_13TeV &> Log_step1
echo "Running run_PrepareSherpaLibs.sh WtoMNu_2j_LO_OpenLoops_CKKW_13TeV "
sh run_PrepareSherpaLibs.sh WtoMNu_2j_LO_OpenLoops_CKKW_13TeV  &> Log_step2

#copy all produced file to EOS
if [ -e "${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}" ];then
    rm ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
fi
mkdir -p ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_crdE.tgz ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}   
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_libs.tgz  ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER.tgz ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_crss.tgz  ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_logL.tgz  ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_migr.tgz ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_13TeV_MASTER.md5 ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER_cff.py ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp MPI_Cross_Sections.dat ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}
scp Log_step1 Log_step2 ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}

#UNLESS you wanna generate some event file here
#assgin sherpack to current dir;
#HERE=`pwd -p`
#sed -e "s,XXX,${HERE}/," sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER_cff.py
################
#scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER_cff.py ../python
#cd ..
#scram b 
#cd test
#echo "Running cmsDriver"
#cmsDriver.py SherpaGeneration/Generator/python/sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER_cff.py -s GEN -n ${nevent} --no_exec --conditions auto:mc --eventcontent RAWSIM &> Log_step3
#echo "Generating Events"
#cmsRun sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER_cff_py_GEN.py &> Log_step4
#echo "DONE --> Output look like this"
#ls
#scp sherpa_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_MASTER_cff_py_GEN.root ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV
#scp Log_step3 Log_step4 ${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV

#
#----------------------------------------------------------
# Clear job and log
#----------------------------------------------------------
#
echo "====== Sherpack is located at ====="
echo "${SherpackLocation}/SHERPA_WtoMNu_2j_LO_OpenLoops_CKKW_13TeV_${CMSSWRELEASE}"
rm -rf ${CODE_SRC}/Log_*
rm -rf ${CODE_SRC}/LSF*
rm -rf ${CODE_SRC}/core*
rm -rf /afs/cern.ch/user/${USER:0:1}/${USER}/LSF*
cd ${WORKDIR}
rm -rf CMSSW*
echo ""
echo "Job end `date`"
echo ""
exit ${status}
